{% set version = "0.13.0" %}

package:
  name: vega3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega3/vega3-{{ version }}.tar.gz
  sha256: 2918a4e4abaef23e0a0fd1a9d5e51baab770ffdf157aac7ac5892eba97a69b33

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - jupyter
  run:
    - python
    - jupyter
    - pandas

test:
  imports:
    - vega3

about:
  home: http://github.com/vega/ipyvega/tree/vega3
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'IPyVega3: An IPython/Jupyter widget for Vega 3 and Vega-Lite 2'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
    - domoritz
