{% set version = "0.11.0" %}

package:
  name: vega3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/vega3/vega3-{{ version }}.tar.gz
  sha256: 5541ff4a972846ccd5e48ad628ffb15c5f50260d5377b6c19bce52c0ff316d71

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - jupyter
  run:
    - python
    - jupyter
    - pandas

test:
  imports:
    - vega3

about:
  home: http://github.com/vega/ipyvega/tree/vega3
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'IPyVega3: An IPython/Jupyter widget for Vega 3 and Vega-Lite 2'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
    - domoritz
