travis:
  secure:
    BINSTAR_TOKEN: iH1ZTZLvCpwBC1HdM0w0J8sW21Uj6Yx1D8bsJ0zFndjKGFiVBR1dDQrqFpMKXziTtUtritibXp6b2aXFZfKDvnn/u3UYCEUrp/vdEfLoAih7HesY86UvB09YsWSG+AT1sPUMDTdj9FcO5QE/mAMd39lNUZOOGa9L+H1P86mG8FOIZtFMEGN8jU3BnZg/mr3fRIPISSUr+sdBBuIl1BxLTonOQtI9tyAoS1uK1x4YY3GXIfqDFNnO2XaRRFlk5iFyOG6zak/CbFLWE5wXyMWzBWAGeyGfT6FPDTXECVF3U62j4c1UGN3POxQ9zlEOjjNk0Aw5yoUil9IwxICXlWUsI8lsXxXtgkDDRViMHRGq6JFL4jZ1Z5qkKPWtfJE21H9KrAKKfBIYeOaR4jPigjkakpcJ03h59NEyMjCypNx3In+kMeWxYnJRApcm7Ej0Wn//pjHarNMWjaeWK8ZBVNWc8Y5Rncf21hnXeZcmCTnfxoSEfKJQ8En68rx8dq//tjMZV7do8WEmE62nScpOwsCQYp5hBxZ4ihf3MbR7xs8e9Bi6zooJVWQ2RZgp2ZRGRK+qEiM8JC0g38yHgXcsmlWfISgKfEznQ3lN76cQWbSjNaedL7dyPYgeuJ9Xm1OKK/9kZ5GiTqhkll4xEhxyWfY1WeBEX0A1TYq6KfXx1utWCpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
