travis:
  secure:
    BINSTAR_TOKEN: a2S9isSGB5/4LsSK88JuTwApN+nN/YYtFG3dgiENMIm7+aLMPnoAcDV70so2nDMql3tg7DB0dT0zV69s178jdW+Wnvartt3gEQfJD9ECICauT7WgHVMDfYetpBAd7Dl0xnUnrDWHFxzI38MuJ+nJpbGZAw69xGxn/b1lfQeiG6xldzkhmGsBBQSAd0hrxfA6LYQdXk6E0Uv+w9yM9ilZL8LHZHAz2CdgFF9ekl4JZej4n4R7nXPSMVrb3cCQDVSoZSTBzj76Mo1a+zGbRq0CaD99g9705XCJJVIPnYPmKFlQfUkQP0H5wRWlXvHf1P7lMtt1W47jdfi41pWA050TIS2Ii124dZx7+Y0bqgNoKLFjv7RbZCt7/lzZMYxbUbJ1XcjrH6GvZKlQmIuo4sDuIpjDZiBX5r1LqJLs5Njdz2sy2ibBVXzzkU+sfSokdaYde5Ax5CaGCiWQOr3lC2Y1aqqjY+NaXSHA9WusM7UFt1c5vRVtdz6GxGANjv6rdi545ASfJIDZqNI2NFgr9/XT1Nvi8fNVjuJL/FArOfqSO32IYxhga7eO87ft40QuEZjI8vvz3nkx+BbKkrG+ptK6YLL3VOGIHosoM4uGjdALeEYkm08gPaODBXOspSyThN0JsAc97NmFniJSvG7ajcXkOd2BYz6jyD531a80OJlvR+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
